---
name: Java Syntax Check

on: [push]

jobs:
  syntax-check:
    name: Syntax Checks
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '19'
        distribution: 'adopt'

    - name: Run Checkstyle
      run: mvn checkstyle:checkstyle

